[package]
authors.workspace       = true
categories.workspace    = true
description             = "Rspack tasks"
documentation.workspace = true
edition.workspace       = true
homepage.workspace      = true
license.workspace       = true
name                    = "rspack_tasks"
repository.workspace    = true
version.workspace       = true

[features]
goexec = ["dep:goexec"]

[dependencies]
goexec = { git = "https://github.com/dudykr/ddbase", rev = "23a076d0d69e4b1a4dfe1ad1d9f20d1bcd4c2f96", optional = true }
tokio = { workspace = true }
[lints]
workspace = true

[lib]
doctest = false
test    = false
